"""empty message

Revision ID: 3652376c3ae6
Revises: f940d56a382f
Create Date: 2019-12-09 13:02:30.920008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3652376c3ae6'
down_revision = 'f940d56a382f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=False))
    op.add_column('Venue', sa.Column('seeking_talent_description', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website')
    op.drop_column('Venue', 'seeking_talent_description')
    op.drop_column('Venue', 'seeking_talent')
    # ### end Alembic commands ###
