"""empty message

Revision ID: 8aa275bb9d4d
Revises: 9f134545069a
Create Date: 2019-12-10 18:58:55.314450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aa275bb9d4d'
down_revision = '9f134545069a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genre', sa.ARRAY(sa.String(length=120)), nullable=True))
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'genre')
    # ### end Alembic commands ###
